# shellcheck shell=bash
# shellcheck disable=SC2015,SC2154  # sourced integration cases share the orchestrator fixture
# --- state model ------------------------------------------------------------
[[ "$(state_json filecopy)" == "new 0" ]] && pass "fresh: filecopy = new, not installed" || fail "fresh: filecopy = new (got '$(state_json filecopy)')"
[[ "$(state_json package)"  == "pkg 0" ]] && pass "fresh: package = package, not installed" || fail "fresh: package state (got '$(state_json package)')"

# --- generated package inventory -------------------------------------------
BREWFILE="$SB/Brewfile"
rc_is "brewfile command exits 0" 0 df brewfile --output "$BREWFILE"
check "brewfile records formulae" grep -Fx 'brew "filecopy"' "$BREWFILE"
check "brewfile records casks" grep -Fx 'cask "vendor/tap/desktop"' "$BREWFILE"
check "brewfile records third-party taps" grep -Fx 'tap "vendor/tap"' "$BREWFILE"
check "brewfile identifies the CLI generator" grep -Fx \
    '# Generated by dotlad brewfile; edit modules/*/module.conf.' "$BREWFILE"
rc_is "brewfile rejects positional arguments" 1 df brewfile extra
rc_is "output option is brewfile-only" 1 df --output "$SB/nope" all

# Plans expose exact pending actions without installing or writing config.
plan_out="$(df plan filecopy)"
printf '%s\n' "$plan_out" | grep -qF 'packages: install filecopy' \
    && pass "plan reports package installation" || fail "plan package action"
printf '%s\n' "$plan_out" | grep -qF 'config:   create' \
    && pass "plan reports config creation" || fail "plan config action"
checknot "plan is read-only" test -e "$H/.config/filecopy/config.toml"
plan_json="$(df plan filecopy --json)"
printf '%s' "$plan_json" | jq -e \
    '.mode == "full" and .modules[0].name == "filecopy" and .modules[0].config == "create"' \
    >/dev/null && pass "plan emits machine-readable JSON" || fail "plan JSON contract"
dry_json="$(df --dry-run --json filecopy)"
[[ "$dry_json" == "$plan_json" ]] && pass "--dry-run matches plan" || fail "dry-run alias"

# --symlink changes only the implicit resolver. Explicit module choices still
# win, and JSON plans expose the effective resolver.
mkdir -p "$FAKE/modules/symlink-flag/files" "$FAKE/modules/explicit-copy/files"
printf 'linked by flag\n' > "$FAKE/modules/symlink-flag/files/config"
printf 'explicit copy\n' > "$FAKE/modules/explicit-copy/files/config"
cat > "$FAKE/modules/symlink-flag/module.conf" <<EOF
NAME="symlink-flag"
DESC="CLI symlink default fixture"
ICON="!"
ORDER="997"
SOURCE="files/config"
DEST="$H/.config/symlink-flag/config"
EOF
cat > "$FAKE/modules/explicit-copy/module.conf" <<EOF
NAME="explicit-copy"
DESC="Explicit copy resolver fixture"
ICON="!"
ORDER="997"
SOURCE="files/config"
DEST="$H/.config/explicit-copy/config"
RESOLVER="copy"
EOF
symlink_flag_plan="$(df plan symlink-flag --symlink --json)"
printf '%s' "$symlink_flag_plan" | jq -e \
    '.modules[0].resolver == "symlink" and .modules[0].changes == "1 link to sync"' >/dev/null \
    && pass "--symlink changes the planned default resolver" \
    || fail "--symlink plan did not expose the effective resolver"
df --config-only symlink-flag --symlink >/dev/null 2>&1
check "--symlink deploys an implicit resolver as a link" test -L "$H/.config/symlink-flag/config"
df --symlink --config-only explicit-copy >/dev/null 2>&1
checknot "explicit copy resolver overrides --symlink" test -L "$H/.config/explicit-copy/config"
check "explicit copy resolver still deploys content" cmp -s \
    "$FAKE/modules/explicit-copy/files/config" "$H/.config/explicit-copy/config"
rm -rf "$FAKE/modules/symlink-flag" "$FAKE/modules/explicit-copy" \
    "$H/.config/symlink-flag" "$H/.config/explicit-copy"

# --- operation modes --------------------------------------------------------
mkdir -p "$FAKE/modules/mode-fixture/files"
printf 'repo = 1\n' > "$FAKE/modules/mode-fixture/files/config.toml"
cat > "$FAKE/modules/mode-fixture/module.conf" <<EOF
NAME="mode-fixture"
DESC="Installer mode fixture"
ICON="!"
ORDER="999"
BREW="mode-pkg"
CHECK="mode-pkg"
SOURCE="files/config.toml"
DEST="$H/.config/mode-fixture/config.toml"
REQUIRES="mode-req"
EOF
: > "$BREW_LOG"
df --packages-only mode-fixture >/dev/null 2>&1
check "packages-only installs the declared package" test -e "$BREW_PREFIX/opt/mode-pkg"
checknot "packages-only does not deploy config" test -e "$H/.config/mode-fixture/config.toml"
checknot "packages-only skips config requirements" grep -qxF mode-req "$BREW_LOG"

rm -rf "$BREW_PREFIX/opt/mode-pkg" "$BREW_PREFIX/bin/mode-pkg"
printf '#!/bin/sh\nexit 0\n' > "$SB/bin/mode-req"; chmod +x "$SB/bin/mode-req"
: > "$BREW_LOG"
df --config-only mode-fixture >/dev/null 2>&1
check "config-only deploys config" cmp -s "$FAKE/modules/mode-fixture/files/config.toml" "$H/.config/mode-fixture/config.toml"
checknot "config-only does not install the declared package" test -e "$BREW_PREFIX/opt/mode-pkg"
checknot "config-only performs no Homebrew install" test -s "$BREW_LOG"

printf 'repo = 2\n' > "$FAKE/modules/mode-fixture/files/config.toml"
rm -f "$SB/bin/mode-req"; : > "$BREW_LOG"
rc_is "config-only reports a missing requirement without installing it" 1 df --config-only mode-fixture
check "failed config-only keeps the deployed config unchanged" grep -qxF 'repo = 1' "$H/.config/mode-fixture/config.toml"
checknot "missing config-only requirement does not invoke Homebrew" test -s "$BREW_LOG"

# Batch preflight prevents an earlier valid module from changing state when a
# later selected module cannot satisfy its config contract.
rm -f "$H/.config/mode-fixture/config.toml"
rc_is "batch preflight fails before mutation" 1 df --config-only multipkg mode-fixture
checknot "batch preflight leaves earlier module untouched" test -e "$H/.config/multipkg/config"

packages_view="$(df --packages-only --plain)"
config_view="$(df --config-only --plain)"
if printf '%s\n' "$packages_view" | grep -q 'jsonmerge'; then
    fail "packages-only hides modules without an installer"
else
    pass "packages-only hides modules without an installer"
fi
if printf '%s\n' "$packages_view" | grep -q 'modules/.*/files'; then
    fail "packages-only hides config activity"
else
    pass "packages-only hides config activity"
fi
if printf '%s\n' "$config_view" | grep -qE '(^|[[:space:]])package([[:space:]]|$)'; then
    fail "config-only hides package-only modules"
else
    pass "config-only hides package-only modules"
fi
rc_is "packages-only rejects a config-only module" 1 df --packages-only jsonmerge
rc_is "config-only rejects a package-only module" 1 df --config-only package

tui_probe="$(cd "$FAKE" && HOME="$H" ROOT="$FAKE" /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"
    DOTLAD_RUNDIR=""; mode_set full
    modes=""
    tui_cycle_mode; modes="$DOTLAD_MODE"
    tui_cycle_mode; modes="$modes $DOTLAD_MODE"
    tui_cycle_mode; modes="$modes $DOTLAD_MODE"
    I_TYPE=(tool sep backup); I_NAME=(filecopy @@sep @backup); N_ITEMS=3; SEL=" "
    toggle_rc=0; tui_toggle_all || toggle_rc=$?
    selected=0; is_selected filecopy && selected=1
    tui_read_key < <(printf "в"); diff_key="$TUI_KEY"
    aliases=""
    for input in о л п П ф ь в ч й н Н; do
        TUI_KEY="$input"; tui_normalize_key
        aliases="${aliases}${TUI_KEY} "
    done
    run="$(mktemp -d)"; queue_rc=0
    queue_out="$(queue_has_tool "$run" filecopy 2>&1)" || queue_rc=$?
    rm -rf "$run"
    queue_quiet=0; [[ -z "$queue_out" ]] && queue_quiet=1
    printf "%s|%s|%s|%s|%s|%s|%s" "$modes" "$toggle_rc" "$selected" \
        "$diff_key" "$aliases" "$queue_rc" "$queue_quiet"')"
IFS='|' read -r mode_cycle toggle_rc toggle_selected diff_key key_aliases queue_rc queue_quiet <<< "$tui_probe"
[[ "$mode_cycle" == "packages config full" ]] && pass "TUI mode switch cycles through all modes" \
    || fail "TUI mode switch cycle (got '$mode_cycle')"
[[ "$toggle_rc|$toggle_selected" == "0|1" ]] && pass "select-all succeeds with restore points after the tools" \
    || fail "select-all restore-point probe (got '$toggle_rc|$toggle_selected')"
[[ "$diff_key" == "в" ]] && pass "TUI reads the Ukrainian diff hotkey as one character" \
    || fail "Ukrainian diff hotkey probe (got '$diff_key')"
[[ "$key_aliases" == "j k g G a m d x q y Y " ]] \
    && pass "TUI normalizes every Ukrainian-layout letter hotkey" \
    || fail "Ukrainian hotkey aliases (got '$key_aliases')"
[[ "$queue_rc|$queue_quiet" == "1|1" ]] && pass "empty TUI run checks a missing queue silently" \
    || fail "missing TUI queue probe (got '$queue_rc|$queue_quiet')"

mkdir -p "$FAKE/modules/worker-fixture/files"
printf 'worker = true\n' > "$FAKE/modules/worker-fixture/files/config.toml"
cat > "$FAKE/modules/worker-fixture/module.conf" <<EOF
NAME="worker-fixture"
DESC="External project worker fixture"
ICON="w"
ORDER="997"
SOURCE="files/config.toml"
DEST="$H/.config/worker-fixture/config.toml"
EOF
worker_probe="$(cd "$FAKE" && HOME="$H" ROOT="$FAKE" \
    DOTLAD_BIN="$DOTLAD_RUNTIME_ROOT/dotlad" \
    DOTLAD_BACKUP_ROOT="$H/.dotlad_backup" DOTLAD_DEFAULT_RESOLVER=symlink /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"
    manifest_load; mode_set config
    DOTLAD_RUNDIR="$(mktemp -d)"; export DOTLAD_RUNDIR
    enqueue worker-fixture
    attempt=0
    while [[ ! -f "$DOTLAD_RUNDIR/worker-fixture.done" \
        && ! -f "$DOTLAD_RUNDIR/worker-fixture.failed" \
        && "$attempt" -lt 100 ]]; do
        sleep 0.05; attempt=$((attempt + 1))
    done
    if [[ -f "$DOTLAD_RUNDIR/worker-fixture.done" \
        && -L "$HOME/.config/worker-fixture/config.toml" ]]; then
        printf done
    else
        printf failed
    fi
    tui_cleanup >/dev/null 2>&1')"
[[ "$worker_probe" == "done" ]] && pass "background worker preserves project root and default resolver" \
    || fail "external project worker probe (got '$worker_probe')"
rm -rf "$FAKE/modules/worker-fixture" "$H/.config/worker-fixture"
rm -rf "$FAKE/modules/mode-fixture" "$H/.config/mode-fixture"
