# shellcheck shell=bash
# shellcheck disable=SC2015,SC2154  # sourced integration cases share the orchestrator fixture
# --- state model ------------------------------------------------------------
[[ "$(state_json filecopy)" == "new 0" ]] && pass "fresh: filecopy = new, not installed" || fail "fresh: filecopy = new (got '$(state_json filecopy)')"
[[ "$(state_json package)" == "pkg 0" ]] && pass "fresh: package = package, not installed" || fail "fresh: package state (got '$(state_json package)')"

# --- generated package inventory -------------------------------------------
BREWFILE="$SB/Brewfile"
rc_is "brewfile command exits 0" 0 df brewfile --output "$BREWFILE"
check "brewfile records formulae" grep -Fx 'brew "filecopy"' "$BREWFILE"
if [[ "$TEST_PLATFORM" == macos ]]; then
    check "macOS Brewfile records casks" grep -Fx 'cask "vendor/tap/desktop"' "$BREWFILE"
else
    checknot "$TEST_PLATFORM Brewfile excludes casks" grep -F 'cask ' "$BREWFILE"
fi
check "brewfile records third-party taps" grep -Fx 'tap "vendor/tap"' "$BREWFILE"
check "brewfile identifies the CLI generator" grep -Fx \
    '# Generated by dotlad brewfile; edit tools/*/tool.conf.' "$BREWFILE"
BRANDED_BREWFILE="$SB/BrandedBrewfile"
(cd "$FAKE" && PATH="$SB/brewprefix/bin:$SB/bin:$PATH" HOME="$H" \
    DOTLAD_YES=1 DOTLAD_PLAIN=1 DOTLAD_COMMAND_NAME=mydots \
    DOTLAD_DISPLAY_NAME='My Dotfiles' /bin/bash "$ROOT/dotlad" \
    "$FAKE" brewfile --output "$BRANDED_BREWFILE" >/dev/null)
check "brewfile attribution uses the display name" grep -Fx \
    '# Generated by My Dotfiles brewfile; edit tools/*/tool.conf.' "$BRANDED_BREWFILE"
rc_is "brewfile rejects positional arguments" 1 df brewfile extra
rc_is "output option is brewfile-only" 1 df --output "$SB/nope" all

# Platform filtering is driven by uname. Manifests without PLATFORMS are
# portable by default; macOS-only casks disappear from Linux and WSL views,
# plans, profiles, and generated Brewfiles. Linux manifests include WSL unless
# a tool explicitly narrows itself to WSL.
LINUX_BIN="$SB/linux-bin"
MACOS_BIN="$SB/macos-bin"
WSL_BIN="$SB/wsl-bin"
mkdir -p "$LINUX_BIN" "$MACOS_BIN" "$WSL_BIN"
cat >"$LINUX_BIN/uname" <<'EOF'
#!/bin/sh
printf 'Linux\n'
EOF
chmod +x "$LINUX_BIN/uname"
cat >"$MACOS_BIN/uname" <<'EOF'
#!/bin/sh
printf 'Darwin\n'
EOF
chmod +x "$MACOS_BIN/uname"
cat >"$WSL_BIN/uname" <<'EOF'
#!/bin/sh
if [ "${1:-}" = -r ]; then
    printf '5.15.153.1-microsoft-standard-WSL2\n'
else
    printf 'Linux\n'
fi
EOF
chmod +x "$WSL_BIN/uname"
linux_df() {
    (
        unset WSL_DISTRO_NAME WSL_INTEROP
        cd "$FAKE" && PATH="$LINUX_BIN:$SB/brewprefix/bin:$SB/bin:$PATH" HOME="$H" \
            DOTLAD_YES=1 DOTLAD_PLAIN=1 /bin/bash "$ROOT/dotlad" \
            "$FAKE" --backup "$H/.dotlad_backup" "$@"
    )
}
wsl_df() {
    (
        unset WSL_DISTRO_NAME WSL_INTEROP
        cd "$FAKE" && PATH="$WSL_BIN:$SB/brewprefix/bin:$SB/bin:$PATH" HOME="$H" \
            DOTLAD_YES=1 DOTLAD_PLAIN=1 /bin/bash "$ROOT/dotlad" \
            "$FAKE" --backup "$H/.dotlad_backup" "$@"
    )
}
macos_df() {
    (cd "$FAKE" && PATH="$MACOS_BIN:$SB/brewprefix/bin:$SB/bin:$PATH" HOME="$H" \
        DOTLAD_YES=1 DOTLAD_PLAIN=1 /bin/bash "$ROOT/dotlad" \
        "$FAKE" --backup "$H/.dotlad_backup" "$@")
}
mkdir -p "$FAKE/tools/wsl-only"
cat >"$FAKE/tools/wsl-only/tool.conf" <<'EOF'
NAME="wsl-only"
DESC="WSL-only package fixture"
ICON="w"
PLATFORMS="wsl"
BREW="wsl-only"
EOF
linux_plan="$(linux_df plan all --json)"
printf '%s' "$linux_plan" | jq -e \
    '.platform == "linux" and any(.tools[]; .name == "filecopy") and all(.tools[]; .name != "desktop" and .name != "wsl-only")' \
    >/dev/null && pass "Linux plans include portable tools and exclude macOS tools" ||
    fail "Linux plan ignores PLATFORMS: $linux_plan"
linux_profile="$(linux_df plan profile base --json)"
printf '%s' "$linux_profile" | jq -e \
    'any(.tools[]; .name == "filecopy") and all(.tools[]; .name != "desktop")' \
    >/dev/null && pass "Linux profiles filter macOS-only tools" ||
    fail "Linux profile ignores PLATFORMS: $linux_profile"
linux_plain="$(linux_df --plain)"
if [[ "$linux_plain" == *filecopy* && "$linux_plain" != *desktop* ]]; then
    pass "Linux state view hides macOS-only tools"
else
    fail "Linux state view ignores PLATFORMS"
fi
linux_explicit_rc=0
linux_explicit_out="$(linux_df plan desktop 2>&1)" || linux_explicit_rc=$?
if [[ "$linux_explicit_rc" == 1 && "$linux_explicit_out" == *'desktop is not available on linux'* ]]; then
    pass "explicit Linux selection explains a platform mismatch"
else
    fail "explicit Linux selection hides its platform mismatch (rc=$linux_explicit_rc: $linux_explicit_out)"
fi
LINUX_BREWFILE="$SB/LinuxBrewfile"
linux_df brewfile --output "$LINUX_BREWFILE" >/dev/null
check "Linux Brewfile includes portable formulae" grep -Fx 'brew "filecopy"' "$LINUX_BREWFILE"
checknot "Linux Brewfile excludes macOS casks" grep -F 'cask ' "$LINUX_BREWFILE"
WSL_BREWFILE="$SB/WSLBrewfile"
wsl_df brewfile --output "$WSL_BREWFILE" >/dev/null
check "WSL inherits portable Linux formulae" grep -Fx 'brew "filecopy"' "$WSL_BREWFILE"
check "WSL includes WSL-only formulae" grep -Fx 'brew "wsl-only"' "$WSL_BREWFILE"
checknot "WSL Brewfile excludes macOS casks" grep -F 'cask ' "$WSL_BREWFILE"
wsl_plan="$(wsl_df plan all --json)"
printf '%s' "$wsl_plan" | jq -e \
    '.platform == "wsl" and any(.tools[]; .name == "filecopy") and any(.tools[]; .name == "wsl-only") and all(.tools[]; .name != "desktop")' \
    >/dev/null && pass "WSL plans inherit Linux tools and include WSL-only tools" ||
    fail "WSL plan ignores platform inheritance: $wsl_plan"
rm -rf "$FAKE/tools/wsl-only"
MACOS_BREWFILE="$SB/MacOSBrewfile"
macos_df brewfile --output "$MACOS_BREWFILE" >/dev/null
check "macOS projection includes macOS casks" \
    grep -Fx 'cask "vendor/tap/desktop"' "$MACOS_BREWFILE"

# Homebrew's Linux installer does not update the parent shell. Discover the
# default Linuxbrew prefix and evaluate its shellenv output explicitly.
LINUX_HOME="$SB/linux-home"
BOOTSTRAP_BIN="$SB/bootstrap-bin"
mkdir -p "$LINUX_HOME/.linuxbrew/bin" "$BOOTSTRAP_BIN"
cat >"$BOOTSTRAP_BIN/uname" <<'EOF'
#!/bin/sh
printf 'Linux\n'
EOF
cat >"$BOOTSTRAP_BIN/curl" <<'EOF'
#!/bin/sh
exit 0
EOF
cat >"$LINUX_HOME/.linuxbrew/bin/brew" <<EOF
#!/bin/sh
if [ "\${1:-}" = shellenv ]; then
    printf '%s\n' 'export PATH="$LINUX_HOME/.linuxbrew/bin:\$PATH"'
fi
EOF
chmod +x "$BOOTSTRAP_BIN/uname" "$BOOTSTRAP_BIN/curl" \
    "$LINUX_HOME/.linuxbrew/bin/brew"
linuxbrew_probe="$(cd "$FAKE" && HOME="$LINUX_HOME" \
    PATH="$BOOTSTRAP_BIN:/usr/bin:/bin" ROOT="$FAKE" /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"
    confirm() { return 0; }
    ensure_brew >/dev/null
    command -v brew')"
[[ "$linuxbrew_probe" == "$LINUX_HOME/.linuxbrew/bin/brew" ]] &&
    pass "Homebrew bootstrap discovers the default Linuxbrew prefix" ||
    fail "Homebrew bootstrap missed Linuxbrew: $linuxbrew_probe"

# Plans expose exact pending actions without installing or writing config.
plan_out="$(df plan filecopy)"
printf '%s\n' "$plan_out" | grep -qF 'packages: install filecopy' &&
    pass "plan reports package installation" || fail "plan package action"
printf '%s\n' "$plan_out" | grep -qF 'config.main         create' &&
    pass "plan reports config creation" || fail "plan config action"
checknot "plan is read-only" test -e "$H/.config/filecopy/config.toml"
plan_json="$(df plan filecopy --json)"
printf '%s' "$plan_json" | jq -e --arg platform "$TEST_PLATFORM" \
    '.platform == $platform and .mode == "full" and .tools[0].name == "filecopy" and .tools[0].configs[0].name == "main" and .tools[0].configs[0].state == "create"' \
    >/dev/null && pass "plan emits machine-readable JSON" || fail "plan JSON contract"
dry_json="$(df --dry-run --json filecopy)"
[[ "$dry_json" == "$plan_json" ]] && pass "--dry-run matches plan" || fail "dry-run alias"
json_control_expected="$(printf 'back\bform\funit\001end')"
json_control_encoded="$(cd "$FAKE" && HOME="$H" ROOT="$FAKE" /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"
    json_string "$1"' _ "$json_control_expected")"
json_control_actual="$(printf '%s' "$json_control_encoded" | jq -r . 2>/dev/null)"
[[ "$json_control_actual" == "$json_control_expected" ]] &&
    pass "plan JSON escapes every control character" ||
    fail "plan JSON emitted an invalid control string"

# Built-in resolvers own their command requirements. Manifest REQUIRES adds
# tool-specific commands, and duplicate names are installed only once.
resolver_requirements_probe="$(cd "$FAKE" &&
    PATH="$SB/brewprefix/bin:$SB/bin:$PATH" HOME="$H" ROOT="$FAKE" \
        /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"; manifest_load
    i="$(tool_find jsonmerge)"
    json_req="$(resolver_requirements json)"
    resolver_json_requires() { printf "resolver-auto-req\n"; }
    T_REQUIRES[$i]="tool-extra-req resolver-auto-req"
    reqs="$(tool_requirements "$i")"; reqs="${reqs//$'\''\n'\''/,}"
    preflight_inspect "$i" || true; missing="$PREFLIGHT_MISSING"
    N_INSTALLED=0; ensure_requirements "$i" >/dev/null || exit 1
    printf "%s|%s|%s|%s|%s|%s" "$json_req" "$reqs" "$missing" "$N_INSTALLED" \
        "$(resolver_requirements toml)" "$(resolver_requirements gitconfig)"')"
if [[ "$resolver_requirements_probe" == "jq|resolver-auto-req,tool-extra-req|resolver-auto-req tool-extra-req|2|yq|git" ]]; then
    pass "resolvers own deduplicated installable requirements"
else
    fail "resolver requirement contract is inconsistent: $resolver_requirements_probe"
fi
rm -rf "$BREW_PREFIX/opt/resolver-auto-req" "$BREW_PREFIX/bin/resolver-auto-req" \
    "$BREW_PREFIX/opt/tool-extra-req" "$BREW_PREFIX/bin/tool-extra-req"

bundled_requirement_probe="$(cd "$FAKE" &&
    PATH="$SB/brewprefix/bin:$SB/bin:$PATH" HOME="$H" ROOT="$FAKE" \
        /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"; manifest_load
    i="$(tool_find jsonmerge)"
    T_REQUIRES[$i]="requirement-provider requirement-command"
    N_INSTALLED=0; ensure_requirements "$i" >/dev/null || exit 1
    printf "%s|%s" "$N_INSTALLED" "$(tail -1 "$BREW_LOG")"')"
[[ "$bundled_requirement_probe" == "1|requirement-provider" ]] &&
    pass "one requirement formula may provide multiple commands" ||
    fail "bundled requirements trigger redundant formula installs: $bundled_requirement_probe"
rm -rf "$BREW_PREFIX/opt/requirement-provider" \
    "$BREW_PREFIX/bin/requirement-provider" "$BREW_PREFIX/bin/requirement-command"

# --symlink changes only the implicit resolver. Explicit tool choices still
# win, and JSON plans expose the effective resolver.
mkdir -p "$FAKE/tools/symlink-flag/files" "$FAKE/tools/explicit-copy/files"
printf 'linked by flag\n' >"$FAKE/tools/symlink-flag/files/config"
printf 'explicit copy\n' >"$FAKE/tools/explicit-copy/files/config"
cat >"$FAKE/tools/symlink-flag/tool.conf" <<EOF
NAME="symlink-flag"
DESC="CLI symlink default fixture"
ICON="!"
ORDER="997"
[config.main]
SOURCE="files/config"
DEST="$H/.config/symlink-flag/config"
EOF
cat >"$FAKE/tools/explicit-copy/tool.conf" <<EOF
NAME="explicit-copy"
DESC="Explicit copy resolver fixture"
ICON="!"
ORDER="997"
[config.main]
SOURCE="files/config"
DEST="$H/.config/explicit-copy/config"
RESOLVER="copy"
EOF
symlink_flag_plan="$(df plan symlink-flag --symlink --json)"
printf '%s' "$symlink_flag_plan" | jq -e \
    '.tools[0].configs[0].resolver == "symlink" and .tools[0].configs[0].changes == "1 link to sync"' >/dev/null &&
    pass "--symlink changes the planned default resolver" ||
    fail "--symlink plan did not expose the effective resolver"
df --config-only symlink-flag --symlink >/dev/null 2>&1
check "--symlink deploys an implicit resolver as a link" test -L "$H/.config/symlink-flag/config"
df --symlink --config-only explicit-copy >/dev/null 2>&1
checknot "explicit copy resolver overrides --symlink" test -L "$H/.config/explicit-copy/config"
check "explicit copy resolver still deploys content" cmp -s \
    "$FAKE/tools/explicit-copy/files/config" "$H/.config/explicit-copy/config"
rm -rf "$FAKE/tools/symlink-flag" "$FAKE/tools/explicit-copy" \
    "$H/.config/symlink-flag" "$H/.config/explicit-copy"

# --- operation modes --------------------------------------------------------
mkdir -p "$FAKE/tools/mode-fixture/files"
printf 'repo = 1\n' >"$FAKE/tools/mode-fixture/files/config.toml"
cat >"$FAKE/tools/mode-fixture/tool.conf" <<EOF
NAME="mode-fixture"
DESC="Installer mode fixture"
ICON="!"
ORDER="999"
BREW="mode-pkg"
CHECK="mode-pkg"
REQUIRES="mode-req"
[config.main]
SOURCE="files/config.toml"
DEST="$H/.config/mode-fixture/config.toml"
EOF
: >"$BREW_LOG"
df --packages-only mode-fixture >/dev/null 2>&1
check "packages-only installs the declared package" test -e "$BREW_PREFIX/opt/mode-pkg"
checknot "packages-only does not deploy config" test -e "$H/.config/mode-fixture/config.toml"
checknot "packages-only skips config requirements" grep -qxF mode-req "$BREW_LOG"

rm -rf "$BREW_PREFIX/opt/mode-pkg" "$BREW_PREFIX/bin/mode-pkg"
printf '#!/bin/sh\nexit 0\n' >"$SB/bin/mode-req"
chmod +x "$SB/bin/mode-req"
: >"$BREW_LOG"
df --config-only mode-fixture >/dev/null 2>&1
check "config-only deploys config" cmp -s "$FAKE/tools/mode-fixture/files/config.toml" "$H/.config/mode-fixture/config.toml"
checknot "config-only does not install the declared package" test -e "$BREW_PREFIX/opt/mode-pkg"
checknot "config-only performs no Homebrew install" test -s "$BREW_LOG"
mode_headline="$(df --plain | grep 'mode-fixture' | head -1)"
if [[ "$mode_headline" == *'not installed'*'config up to date'* &&
    "$mode_headline" != *'✓'* ]]; then
    pass "missing package dominates a ready config headline"
else
    fail "ready config masks a missing package: $mode_headline"
fi

printf 'repo = 2\n' >"$FAKE/tools/mode-fixture/files/config.toml"
rm -f "$SB/bin/mode-req"
: >"$BREW_LOG"
rc_is "config-only reports a missing requirement without installing it" 1 df --config-only mode-fixture
check "failed config-only keeps the deployed config unchanged" grep -qxF 'repo = 1' "$H/.config/mode-fixture/config.toml"
checknot "missing config-only requirement does not invoke Homebrew" test -s "$BREW_LOG"

# Batch preflight prevents an earlier valid tool from changing state when a
# later selected tool cannot satisfy its config contract.
rm -f "$H/.config/mode-fixture/config.toml"
rc_is "batch preflight fails before mutation" 1 df --config-only multipkg mode-fixture
checknot "batch preflight leaves earlier tool untouched" test -e "$H/.config/multipkg/config"

packages_view="$(df --packages-only --plain)"
config_view="$(df --config-only --plain)"
if printf '%s\n' "$packages_view" | grep -q 'jsonmerge'; then
    fail "packages-only hides tools without an installer"
else
    pass "packages-only hides tools without an installer"
fi
if printf '%s\n' "$packages_view" | grep -q 'tools/.*/files'; then
    fail "packages-only hides config activity"
else
    pass "packages-only hides config activity"
fi
if printf '%s\n' "$config_view" | grep -qE '(^|[[:space:]])package([[:space:]]|$)'; then
    fail "config-only hides package-only tools"
else
    pass "config-only hides package-only tools"
fi
rc_is "packages-only rejects a config-only tool" 1 df --packages-only jsonmerge
rc_is "config-only rejects a package-only tool" 1 df --config-only package

# A mode with no relevant tools is an explicit error, not a misleading config
# prompt followed by a successful no-op.
EMPTY_MODE_ROOT="$SB/empty-mode-project"
mkdir -p "$EMPTY_MODE_ROOT/tools/config-only/files"
printf 'config only\n' >"$EMPTY_MODE_ROOT/tools/config-only/files/config"
cat >"$EMPTY_MODE_ROOT/tools/config-only/tool.conf" <<EOF
NAME="config-only"
DESC="Config-only empty-mode fixture"
ICON="!"
[config.main]
SOURCE="files/config"
DEST="$H/.config/empty-mode/config"
EOF
empty_mode_rc=0
empty_mode_out="$(cd "$EMPTY_MODE_ROOT" && HOME="$H" DOTLAD_PLAIN=1 DOTLAD_YES=1 \
    /bin/bash "$ROOT/dotlad" --packages-only all 2>&1)" || empty_mode_rc=$?
if [[ "$empty_mode_rc" == 1 && "$empty_mode_out" == *'no tools for packages only mode'* ]]; then
    pass "all rejects a mode with no relevant tools"
else
    fail "empty-mode all is a successful or misleading no-op (rc=$empty_mode_rc: $empty_mode_out)"
fi
empty_picker_rc=0
empty_picker_out="$(cd "$EMPTY_MODE_ROOT" && HOME="$H" DOTLAD_PLAIN=1 \
    /bin/bash "$ROOT/dotlad" --packages-only 2>&1)" || empty_picker_rc=$?
if [[ "$empty_picker_rc" == 1 && "$empty_picker_out" == *'no tools for packages only mode'* ]]; then
    pass "picker reports an empty operation mode"
else
    fail "empty-mode picker has no explicit state (rc=$empty_picker_rc: $empty_picker_out)"
fi
empty_tui_probe="$(cd "$EMPTY_MODE_ROOT" && HOME="$H" ROOT="$EMPTY_MODE_ROOT" \
    DOTLAD_PLAIN=1 /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"
    manifest_load; DOTLAD_RUNDIR=""; mode_set packages
    CURSOR=0; CUR_NAME=""; SEL=" "; COLS=80; ACTIVITY_WIDTH=76
    TUI_BACKUP_CHILD_ROWS=0; TOAST=""
    tui_scan; tui_build; tui_fix_cursor
    tui_move 1 || exit 1
    tui_enter || exit 1
    printf "%s|%s|%s" "$N_ITEMS" "${I_TYPE[$CURSOR]}" "$TOAST"')"
if [[ "$empty_tui_probe" == '1|empty|no tools for packages only mode' ]]; then
    pass "TUI keeps an actionable empty-mode state"
else
    fail "TUI empty mode crashes or exposes an invalid item: $empty_tui_probe"
fi
rm -rf "$EMPTY_MODE_ROOT"

tui_probe="$(cd "$FAKE" && HOME="$H" ROOT="$FAKE" /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"
    manifest_load; DOTLAD_RUNDIR=""; mode_set full
    modes=""
    tui_cycle_mode; modes="$DOTLAD_MODE"
    tui_cycle_mode; modes="$modes $DOTLAD_MODE"
    tui_cycle_mode; modes="$modes $DOTLAD_MODE"
    I_TYPE=(tool sep backup); I_NAME=(filecopy @@sep @backup); N_ITEMS=3; SEL=" "
    toggle_rc=0; tui_toggle_all || toggle_rc=$?
    selected=0; tui_selection_contains filecopy && selected=1
    tui_read_key < <(printf "в"); diff_key="$TUI_KEY"
    apostrophe="$(printf "\047")"; quote="$(printf "\042")"; backtick="$(printf "\140")"
    layout_inputs=(
        й ц у к е н г ш щ з х ї ф і в а п р о л д ж є я ч с м и т ь б ю ґ
        Й Ц У К Е Н Г Ш Щ З Х Ї Ф І В А П Р О Л Д Ж Є Я Ч С М И Т Ь Б Ю Ґ
    )
    layout_expected=(
        q w e r t y u i o p "[" "]" a s d f g h j k l ";" "$apostrophe"
        z x c v b n m "," "." "$backtick"
        Q W E R T Y U I O P "{" "}" A S D F G H J K L ":" "$quote"
        Z X C V B N M "<" ">" "~"
    )
    layout_ok=1
    for (( alias_i = 0; alias_i < ${#layout_inputs[@]}; alias_i++ )); do
        TUI_KEY="${layout_inputs[$alias_i]}"; tui_normalize_key
        if [[ "$TUI_KEY" != "${layout_expected[$alias_i]}" ]]; then
            layout_ok=0; break
        fi
    done
    run="$(mktemp -d)"; queue_rc=0
    queue_out="$(queue_has_tool "$run" filecopy 2>&1)" || queue_rc=$?
    rm -rf "$run"
    queue_quiet=0; [[ -z "$queue_out" ]] && queue_quiet=1
    log_heights="$(tui_log_height 24 3 0) $(tui_log_height 24 100 0) \
$(tui_log_height 24 100 1) $(tui_log_height 42 100 0) $(tui_log_height 42 100 1)"
    I_TYPE=(tool); I_NAME=(filecopy); CURSOR=0; SEL=" "; enqueue_calls=0; confirm_message=""
    enqueue() { enqueue_calls=$((enqueue_calls + 1)); }
    tui_confirm() { confirm_message="$1"; return 1; }
    tui_enter
    apply_cancel="$enqueue_calls:$TOAST:$confirm_message"
    tui_confirm() { return 0; }
    tui_enter
    apply_confirm="$enqueue_calls"
    tui_confirm() { confirm_message="$1"; return 1; }
    I_NAME=(package); tui_enter; package_prompt="$confirm_message"
    I_NAME=(jsonmerge); tui_enter; config_prompt="$confirm_message"
    printf "%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s" "$modes" "$toggle_rc" "$selected" \
        "$diff_key" "$layout_ok" "$queue_rc" "$queue_quiet" "$log_heights" \
        "$apply_cancel" "$apply_confirm" "$package_prompt" "$config_prompt"')"
IFS='|' read -r mode_cycle toggle_rc toggle_selected diff_key layout_ok queue_rc queue_quiet \
    log_heights apply_cancel apply_confirm package_prompt config_prompt <<<"$tui_probe"
[[ "$mode_cycle" == "packages config full" ]] && pass "TUI mode switch cycles through all modes" ||
    fail "TUI mode switch cycle (got '$mode_cycle')"
[[ "$toggle_rc|$toggle_selected" == "0|1" ]] && pass "select-all succeeds with restore points after the tools" ||
    fail "select-all restore-point probe (got '$toggle_rc|$toggle_selected')"
[[ "$diff_key" == "в" ]] && pass "TUI reads the Ukrainian diff hotkey as one character" ||
    fail "Ukrainian diff hotkey probe (got '$diff_key')"
[[ "$layout_ok" == 1 ]] &&
    pass "TUI normalizes every Ukrainian-layout letter hotkey" ||
    fail "Ukrainian keyboard normalization is incomplete"
[[ "$queue_rc|$queue_quiet" == "1|1" ]] && pass "empty TUI run checks a missing queue silently" ||
    fail "missing TUI queue probe (got '$queue_rc|$queue_quiet')"

lock_probe="$(cd "$FAKE" && HOME="$H" ROOT="$FAKE" /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"
    QUEUE_LOCK_RETRIES=0
    run="$(mktemp -d)"
    mkdir "$run/queue.lock"
    printf "%s" "$$" >"$run/queue.lock/owner"
    live_rc=0; queue_lock "$run" || live_rc=$?
    live_intact=0; [[ -d "$run/queue.lock" ]] && live_intact=1
    printf "%s" 99999999 >"$run/queue.lock/owner"
    stale_rc=0; queue_lock "$run" || stale_rc=$?
    stale_owner="$(cat "$run/queue.lock/owner" 2>/dev/null || true)"
    queue_unlock "$run" || true
    printf "%s:%s:%s:%s:%s" "$live_rc" "$live_intact" "$stale_rc" "$stale_owner" "$$"
    rm -rf "$run"')"
IFS=: read -r live_lock_rc live_lock_intact stale_lock_rc stale_lock_owner lock_probe_pid \
    <<<"$lock_probe"
[[ "$live_lock_rc|$live_lock_intact" == "1|1" ]] &&
    pass "queue lock never steals ownership from a live process" ||
    fail "queue lock stole a live lock ($lock_probe)"
[[ "$stale_lock_rc|$stale_lock_owner" == "0|$lock_probe_pid" ]] &&
    pass "queue lock reclaims a dead process lock" ||
    fail "queue lock did not recover a stale lock ($lock_probe)"

worker_signal_probe="$(cd "$FAKE" && HOME="$H" ROOT="$FAKE" /bin/bash -c '
    run="$(mktemp -d)"
    export DOTLAD_RUNDIR="$run"
    mkdir "$run/queue.lock"
    printf "%s" "$$" >"$run/queue.lock/owner"
    QUEUE_LOCK_RETRIES=0 "$DOTLAD_RUNTIME_ROOT/dotlad" "$ROOT" _worker &
    worker_pid=$!
    attempt=0
    while [[ ! -d "$run/worker.lock" && "$attempt" -lt 100 ]]; do
        sleep 0.02; attempt=$((attempt + 1))
    done
    kill -TERM "$worker_pid" 2>/dev/null || true
    worker_rc=0; wait "$worker_pid" 2>/dev/null || worker_rc=$?
    cleanup_ok=0
    [[ ! -e "$run/worker.pid" && ! -d "$run/worker.lock" ]] && cleanup_ok=1
    foreign_lock_ok=0
    [[ "$(cat "$run/queue.lock/owner" 2>/dev/null)" == "$$" ]] && foreign_lock_ok=1
    printf "%s:%s:%s" "$worker_rc" "$cleanup_ok" "$foreign_lock_ok"
    rm -rf "$run"')"
[[ "$worker_signal_probe" == "143:1:1" ]] &&
    pass "terminated worker cleans up without removing another process lock" ||
    fail "worker signal cleanup is unsafe ($worker_signal_probe)"
[[ "$log_heights" == "3 7 14 13 26" ]] &&
    pass "log panel fits content and expands when focused" ||
    fail "log panel height ignores content or focus (got '$log_heights')"
if [[ "$apply_cancel" == *'0:apply cancelled:'*"Install packages and deploy config for 'filecopy'?"* &&
    "$apply_confirm" == 1 ]]; then
    pass "TUI apply requires explicit confirmation before queueing"
else
    fail "TUI apply confirmation is ineffective ($apply_cancel / $apply_confirm)"
fi
if [[ "$package_prompt" == "Install packages for 'package'?" &&
    "$config_prompt" == "Deploy config for 'jsonmerge'? (replaced files are backed up)" ]]; then
    pass "TUI confirmation describes only selected tool actions"
else
    fail "TUI confirmation mislabels package/config tools ($package_prompt / $config_prompt)"
fi

mkdir -p "$FAKE/tools/worker-fixture/files"
printf 'worker = true\n' >"$FAKE/tools/worker-fixture/files/config.toml"
cat >"$FAKE/tools/worker-fixture/tool.conf" <<EOF
NAME="worker-fixture"
DESC="External project worker fixture"
ICON="w"
ORDER="997"
[config.main]
SOURCE="files/config.toml"
DEST="$H/.config/worker-fixture/config.toml"
EOF
worker_probe="$(cd "$FAKE" && HOME="$H" ROOT="$FAKE" \
    DOTLAD_BIN="$DOTLAD_RUNTIME_ROOT/dotlad" \
    DOTLAD_BACKUP_ROOT="$H/.dotlad_backup" DOTLAD_DEFAULT_RESOLVER=symlink /bin/bash -c '
    . "$DOTLAD_RUNTIME_ROOT/lib/runtime.sh"
    manifest_load; mode_set config
    DOTLAD_RUNDIR="$(mktemp -d)"; export DOTLAD_RUNDIR
    enqueue worker-fixture
    attempt=0
    while [[ ! -f "$DOTLAD_RUNDIR/worker-fixture.done" \
        && ! -f "$DOTLAD_RUNDIR/worker-fixture.failed" \
        && "$attempt" -lt 100 ]]; do
        sleep 0.05; attempt=$((attempt + 1))
    done
    if [[ -f "$DOTLAD_RUNDIR/worker-fixture.done" \
        && -L "$HOME/.config/worker-fixture/config.toml" ]]; then
        printf done
    else
        printf "failed: %s" "$(cat "$DOTLAD_RUNDIR/worker-fixture.log" 2>/dev/null)"
    fi
    tui_cleanup >/dev/null 2>&1')"
[[ "$worker_probe" == "done" ]] && pass "background worker preserves project root and default resolver" ||
    fail "external project worker probe (got '$worker_probe')"
rm -rf "$FAKE/tools/worker-fixture" "$H/.config/worker-fixture"
rm -rf "$FAKE/tools/mode-fixture" "$H/.config/mode-fixture"
