# lib/brewfile.sh — generate Homebrew Bundle metadata from manifests.

cmd_brewfile() (
    local output="${DOTLAD_BREWFILE_OUT:-$PWD/Brewfile}"
    local parent temp work body taps i package tap
    case "$output" in /*) ;; *) output="$PWD/$output" ;; esac
    parent="$(dirname "$output")"
    temp=""
    work=""
    # ShellCheck cannot see that the signal/exit trap invokes this handler.
    # shellcheck disable=SC2317,SC2329
    cleanup_brewfile() {
        [[ -z "$temp" || ! -e "$temp" ]] || rm -f "$temp"
        [[ -z "$work" || ! -e "$work" ]] || rm -rf "$work"
    }
    trap cleanup_brewfile EXIT HUP INT TERM

    manifest_load
    mkdir -p "$parent"
    temp="$(mktemp "$output.XXXXXX")"
    work="$(mktemp -d "${TMPDIR:-/tmp}/dotlad-brewfile.XXXXXX")"
    body="$work/body"
    taps="$work/taps"
    : >"$body"
    : >"$taps"

    while IFS=$'\t' read -r _ i; do
        [[ -n "${T_BREW[$i]}" ]] || continue
        printf '# %s: %s\n' "${T_NAME[$i]}" "${T_DESC[$i]}" >>"$body"
        for package in ${T_BREW[$i]}; do
            if [[ "${T_CASK[$i]}" == "1" ]]; then
                printf 'cask "%s"\n' "$package" >>"$body"
            else
                printf 'brew "%s"\n' "$package" >>"$body"
            fi
            case "$package" in
                */*/*) printf '%s\n' "${package%/*}" >>"$taps" ;;
            esac
        done
    done < <(
        for ((i = 0; i < T_COUNT; i++)); do
            printf '%s\t%s\n' "${T_NAME[$i]}" "$i"
        done | sort
    )

    {
        printf '# Generated by %s brewfile; edit tools/*/tool.conf.\n' "$DOTLAD_DISPLAY_NAME"
        sort -u "$taps" | while IFS= read -r tap; do
            [[ -n "$tap" ]] && printf 'tap "%s"\n' "$tap"
        done
        cat "$body"
    } >"$temp"

    chmod 0644 "$temp"
    mv "$temp" "$output"
    temp=""
    rm -rf "$work"
    work=""
    printf 'Wrote %s\n' "$output"
)
